spring:
  profiles:
    active: home
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&defaultCharset=utf8
    driver-class-name: com.mysql.jdbc.Driver



